# Generated by Django 4.2.10 on 2024-04-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlipFlopWeb', '0002_communities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communities',
            options={'managed': False},
        ),
    ]
