# Generated by Django 4.2.10 on 2024-04-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlipFlopWeb', '0003_alter_communities_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='communities',
            table='communities',
        ),
    ]
