# Generated by Django 4.2.10 on 2024-04-02 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlipFlopWeb', '0004_alter_communities_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='communities',
            table='questions',
        ),
    ]
