# Generated by Django 4.2.10 on 2024-04-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlipFlopWeb', '0005_alter_communities_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('index', models.IntegerField()),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='communities',
            table='communities',
        ),
    ]
